Add helpful error message for missing code example
Before:

```
bin/doc:27:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)

  ruby_code = formatted_comments.match(/~~~ruby\\n([\\S\\s]*)~~~/)[1]
                                                               ^^^
        from bin/doc:17:in `each'
        from bin/doc:17:in `<main>'
```

After:

```
bin/doc:30:in `block in <main>': Missing ruby example in /Users/hartley/src/github.com/kddnewton/yarv/lib/yarv/insn/expandarray.rb doc comment (RuntimeError)
        from bin/doc:17:in `each'
        from bin/doc:17:in `<main>'
```